### ISSUE TITLE
documentation

### ISSUE THREAD

**Issue by ajaymore** [maichong/flow-mongoose#1]
Hi @maichonglyd,

Thank you for this code.

Can you please provide documentation on how to use this library. I am not so good at flow, so can't figure out how to integrate it.

**Comment by maichonglyd** [comment]
The library has been integrated into the `flow-declarations`, you can refer to https://github.com/maichong/flow-declarations ,There are flow definitions for various common libraries. Have a nice day.

**Comment by ajaymore** [comment]
Thank you.
